# Generated by Django 4.1.7 on 2023-02-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spices',
            new_name='Spice',
        ),
    ]
